MODEL:
  TYPE: swin
  NAME: ds_swin_base_patch4_window7_224
  DROP_PATH_RATE: 0.1
  DIS: cosine
  ATTN:
    FEATURE_DIM: 256  # 601
    HEADS: 4
    HIDDEN_DIM: 512

  SWIN: 
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 7

RETURN_PATH: False
VAL: False

TRAIN:
  START_EPOCH: 0
  #BASE_LR: 5e-6
  BASE_LR: 0.02
  DECAY1: 1.   # attn
  DECAY2: 1.   # bott
  DECAY3: 1.   # clf
  EPOCHS: 200
  R: 0.1
#  BASE_LR: 1e-5
#  MIN_LR_MULT: 0.5
#  WEIGHT_DECAY: 1e-4
#  BIAS_WEIGHT_DECAY: 1e-4
#  WARMUP_EPOCHS: 10
#  WARMUP_LR_MULT: 0.05

DATA:
  MEAN: (0.485, 0.456, 0.406)
  STD: (0.229, 0.224, 0.225)
  
